### PR TITLE
add entry_point function

### PR DESCRIPTION
**Pull request by autodataming**
add entry_point function

### CODE REVIEW

**Comment by cxhernandez** [comment]
Not sure how this adds anything....

**Comment by autodataming** [comment]
every script in the scripts dir should have "entry_point " functions.  But in the script of CalculateClusterRadii.py, there is no function "entry_point". After you build the msmbuilder, the command "CalculateClusterRadii" in the dir  "~/miniconda2/bin/'. So you run the command ''CalculateClusterRadii“，it will report an error, ImportError: 'module' object has no attribute 'entry_point'.  So we modified the script "CalculateClusterRadii.py".

**Comment by autodataming** [comment]
To solve the problem, please merge the commit.

**Comment by mpharrigan** [comment]
Hi @autodataming,
This version of msmbuilder is no longer maintained. As such, we won't be merging your pull request. We're glad you could solve your problem, though. We encourage you to port your workflow to msmbuilder 3 at your convenience.

**Pull request closed without merging**
